import {
  SUBMIT_TRIXTA_ACTION_RESPONSE,
  SUBMIT_TRIXTA_ACTION_RESPONSE_FAILURE,
  SUBMIT_TRIXTA_ACTION_RESPONSE_SUCCESS,
  UPDATE_TRIXTA_ACTION,
  UPDATE_TRIXTA_ACTION_RESPONSE,
} from './actions';
import {
  SUBMIT_TRIXTA_REACTION_RESPONSE,
  SUBMIT_TRIXTA_REACTION_RESPONSE_FAILURE,
  SUBMIT_TRIXTA_REACTION_RESPONSE_SUCCESS,
  TRIXTA_REACTION_RESPONSE,
  UPDATE_TRIXTA_REACTION,
  UPDATE_TRIXTA_REACTION_RESPONSE,
} from './reactions';
export * from './actions';
export * from './reactions';
export const UPDATE_TRIXTA_ROLES = `@trixta/trixta-js/UPDATE_TRIXTA_ROLES`;
export const UPDATE_TRIXTA_ROLE = `@trixta/trixta-js/UPDATE_TRIXTA_ROLE`;
export const JOIN_TRIXTA_ROLE = `@trixta/trixta-js/JOIN_TRIXTA_ROLE`;
export const REMOVE_TRIXTA_ROLE = `@trixta/trixta-js/REMOVE_TRIXTA_ROLE`;
export const SIGN_OUT_TRIXTA = `@trixta/trixta-js/SIGN_OUT_TRIXTA`;
export const UPDATE_TRIXTA_ERROR = `@trixta/trixta-js/UPDATE_TRIXTA_ERROR`;

export const trixtaActionTypes = {
  SIGN_OUT_TRIXTA,
  UPDATE_TRIXTA_ROLES,
  UPDATE_TRIXTA_ROLE,
  REMOVE_TRIXTA_ROLE,
  TRIXTA_REACTION_RESPONSE,
  SUBMIT_TRIXTA_REACTION_RESPONSE,
  SUBMIT_TRIXTA_REACTION_RESPONSE_FAILURE,
  SUBMIT_TRIXTA_REACTION_RESPONSE_SUCCESS,
  SUBMIT_TRIXTA_ACTION_RESPONSE,
  SUBMIT_TRIXTA_ACTION_RESPONSE_FAILURE,
  SUBMIT_TRIXTA_ACTION_RESPONSE_SUCCESS,
  UPDATE_TRIXTA_ACTION_RESPONSE,
  UPDATE_TRIXTA_ACTION,
  UPDATE_TRIXTA_REACTION,
  UPDATE_TRIXTA_REACTION_RESPONSE,
  UPDATE_TRIXTA_ERROR,
};
