name: publish-storybook

  workflow_dispatch:

        - name: Install 💿
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Build library 🔨
        run: yarn build

      - name: Build storybook 📖
        run: yarn build-storybook-docs

      - name: Deploy storybook 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
          CLEAN: true
