name: publish-storybook

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publishing latest story
    runs-on: ubuntu-latest
    steps:
    - name: 🛒 Checkout code
    - uses: actions/checkout@v2

    - name: 🧩 Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --prefer-offline --frozen-lockfile

    - name: Build storybook 📖
      run: yarn build-storybook-docs

    - name: Deploy storybook 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH: gh-pages
        FOLDER: storybook-static
        CLEAN: true
